name: build

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Linux AMD64
      run: go build -v -o dwarf2json-linux-amd64
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Build Windows AMD64
      run: go build -v -o dwarf2json-windows-amd64.exe
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Build Darwin AMD64
      run: go build -v -o dwarf2json-darwin-amd64
      env:
        GOOS: darwin
        GOARCH: amd64

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dwarf2json
        path: |
          dwarf2json-linux-amd64
          dwarf2json-windows-amd64.exe
          dwarf2json-darwin-amd64

    - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

    - name: Upload binary - Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dwarf2json-linux-amd64
          asset_name: dwarf2json-linux-amd64
          asset_content_type: application/octet-stream

    - name: Upload binary - Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dwarf2json-windows-amd64.exe
          asset_name: dwarf2json-windows-amd64.exe
          asset_content_type: application/octet-stream

    - name: Upload binary - Mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dwarf2json-darwin-amd64
          asset_name: dwarf2json-darwin-amd64
          asset_content_type: application/octet-stream
